#!/bin/bash

bundle check || bundle install
bundle exec rake db:create db:migrate seed:migrate
bundle exec rake assets:precompile
# bundle exec rake environment elasticsearch:import:model CLASS='Product' FORCE=y &
# bundle exec rake environment elasticsearch:import:model CLASS='Tag' FORCE=y &
rm -f tmp/pids/server.pid
# bundle exec rails s -p 3000 -b '0.0.0.0'
bundle exec puma -C config/puma.rb
